modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL="https://github.com/ChloePrime/sgui-forge/issues" #optional
license = "LGPLv3"

[[mods]]
modId = "sgui"
version = "${version}"
displayName = "Forge PB4 Server GUI"
authors = "Patbox(Original), ChloePrime(Porter)"
credits="aws404"
description = '''
Library for creating server side guis!
'''
logoFile = "assets/icon.png"
displayTest="IGNORE_SERVER_VERSION"

[[dependencies.sgui]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sgui]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sgui]]
modId = "fabric_api" # Use [Forgefied Fabric API](https://www.curseforge.com/minecraft/mc-mods/forgified-fabric-api)
mandatory = true
versionRange = "[0.83,)"
ordering = "NONE"
side = "BOTH"
